/*
 * Description: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *              By starting with 1 and 2, the first 10 terms will be:
 *              1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * Mission:     By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 *              find the sum of the even-valued terms.
 *
 * Author:      Sierikov Artem  (https://github.com/ArtemSer)
 */
package Level_1;

public class Problem_002 {
    public static void main(String[] args) {
        int currentNumber = 0, result = 0, nextNumber = 1, sum;
        while (currentNumber <= 4000000) {
            sum = currentNumber + nextNumber;
            currentNumber = nextNumber;
            nextNumber = sum;
            if (currentNumber % 2 == 0) result += currentNumber;
        }
        System.out.println("Result is: " + result);
    }
}
