/*
 * Description: The sequence of triangle numbers is generated by adding the natural numbers.
 *              So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *              1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *              Let us list the factors of the first seven triangle numbers:
 *              1: 1
 *              3: 1,3
 *              6: 1,2,3,6
 *              10: 1,2,5,10
 *              15: 1,3,5,15
 *              21: 1,3,7,21
 *              28: 1,2,4,7,14,28
 *              We can see that 28 is the first triangle number to have over five divisors.
 * Mission:     What is the value of the first triangle number to have over five hundred divisors?
 *
 * Author:      Sierikov Artem  (https://github.com/ArtemSer)
 */
package Level_1;

public class Problem_012 {
    private static int checkAmountOfDivisors(int numberToCheck) {
        int divisorsCount = 2;
        for (int i = 2; i <= Math.sqrt(numberToCheck); ++i)
            if (numberToCheck % i == 0)
                divisorsCount += (numberToCheck / i == i) ? 1 : 2;
        return divisorsCount;
    }

    public static void main(String[] args) {
        int temp = 0;
        for (int number = 0, add = 1; temp < 500; add++) {
            number += add;
            temp = checkAmountOfDivisors(number);
            System.out.println(number + " divisors: " + temp);
            if (temp > 500) System.out.println("FOUND : ");
        }
    }
}
